name: WZR Mines Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать код
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Установить зависимости
        run: pip install -r requirements.txt

      - name: Запустить бота
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python main.py
